(()=>{
const E=[];const ui={};const init={};
const add=(id,name,cat,desc,keys,html,fn)=>{E.push({id,name,cat,desc,keys});ui[id]=html;init[id]=fn};
const esc=s=>String(s).replace(/[&<>"']/g,c=>c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':c==='"'?'&quot;':'&#039;');
const field=(label,id,ph='')=>'<label>'+esc(label)+'<textarea id="'+id+'" placeholder="'+esc(ph)+'"></textarea></label>';
const input=(label,id,ph='')=>'<label>'+esc(label)+'<input id="'+id+'" placeholder="'+esc(ph)+'"></label>';
const bar=a=>'<button id="run" class="primary">'+a+'</button><pre id="out" class="code"></pre>';
const json=s=>{try{return JSON.parse(s)}catch{return null}};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
function ts(v,n='Root',defs=[]){
  if(v&&typeof v==='object'&&!Array.isArray(v)){
    const name=(n.replace(/[^A-Za-z0-9_$]/g,'')||'Root');
    if(!defs.some(x=>x.name===name)){
      const rows=Object.entries(v).map(([k,x])=>{
        const child=k[0]?k[0].toUpperCase()+k.slice(1):'Field';
        let typ=typeof x;
        if(x===null)typ='unknown';
        else if(Array.isArray(x)){typ=x.length&&typeof x[0]==='object'?child+'Item':(x.length?typeof x[0]:'unknown')+'[]';if(x.length&&typeof x[0]==='object')ts(x[0],child+'Item',defs);}
        else if(typeof x==='object'){typ=child;ts(x,child,defs);}
        return '  '+(/^[A-Za-z_$][\w$]*$/.test(k)?k:JSON.stringify(k))+': '+typ+';';
      }).join('\n');
      defs.push({name,body:rows});
    }
  }
  return defs;
}
function schema(v){if(v===null)return{type:'null'};if(Array.isArray(v))return{type:'array',items:v[0]?schema(v[0]):{}};if(typeof v==='object')return{type:'object',properties:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,schema(x)]))};return{type:typeof v}}
const words=s=>s.trim().replace(/([a-z\d])([A-Z])/g,'$1 $2').replace(/[^A-Za-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean).map(x=>x.toLowerCase());
const cases=(s,t)=>{const w=words(s);if(t==='camel')return w.map((x,i)=>i?x[0].toUpperCase()+x.slice(1):x).join('');if(t==='pascal')return w.map(x=>x[0].toUpperCase()+x.slice(1)).join('');if(t==='snake')return w.join('_');if(t==='kebab')return w.join('-');return w.join('_').toUpperCase()};
const b64e=s=>btoa(unescape(encodeURIComponent(s))),b64d=s=>decodeURIComponent(escape(atob(s)));
function cidr(s){const [ip,pre]=s.trim().split('/'),p=Number(pre);if(!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(ip)||p<0||p>32)return null;const a=ip.split('.').map(Number);if(a.some(x=>x>255))return null;const v=a.reduce((n,x)=>(n*256+x)>>>0,0),m=p?((0xffffffff<<(32-p))>>>0):0,n=(v&m)>>>0,b=(n+(2**(32-p)-1))>>>0,f=x=>[x>>>24,(x>>>16)&255,(x>>>8)&255,x&255].join('.');return{network:f(n),broadcast:f(b),first:p>=31?f(n):f(n+1),last:p>=31?f(b):f(b-1),hosts:p>=31?2**(32-p):Math.max(0,2**(32-p)-2),mask:f(m)}}
add('json-ts','JSON → TypeScript','JSON & Data','Generate TypeScript interfaces from JSON.','json typescript interface generator',field('Sample JSON','input','{"user":{"id":1,"name":"Deden"}}')+input('Root type','root','Root')+bar('Generate'),()=>{const v=json(input.value);out.textContent=v===null?'Invalid JSON':ts(v,root.value||'Root').map(d=>'export interface '+d.name+' {\n'+d.body+'\n}').join('\n\n')});
add('json-schema','JSON Schema Generator','JSON & Data','Generate JSON Schema from sample data.','json schema draft',field('Sample JSON','input','{"name":"DevLens","count":1}')+bar('Generate'),()=>{const v=json(input.value);out.textContent=v===null?'Invalid JSON':JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',...schema(v)},null,2)});
add('mock-json','Mock JSON Generator','JSON & Data','Generate API fixtures from field definitions.','mock fake fixture api',field('Fields','input','name:string\nage:number\nactive:boolean\nemail:email')+input('Count','count','3')+bar('Generate'),()=>{const defs=input.value.split(/\n/).map(x=>x.split(':')).filter(x=>x.length>1),n=Math.max(1,Math.min(100,Number(count.value)||1));const val=(t,i)=>t==='number'?i+1:t==='boolean'?i%2===0:t==='email'?'user'+(i+1)+'@example.com':t==='uuid'?crypto.randomUUID():t+'-'+(i+1);out.textContent=JSON.stringify(Array.from({length:n},(_,i)=>Object.fromEntries(defs.map(([k,t])=>[k,val(t.trim(),i)]))),null,2)});
add('uuid','UUID Generator & Validator','Security','Generate and validate UUID v4 locally.','uuid guid identifier','<button id="generate" class="primary">Generate UUID</button><button id="validate">Validate</button>'+input('UUID','input','UUID v4')+'<pre id="out" class="code"></pre>',()=>{generate.onclick=()=>input.value=crypto.randomUUID();validate.onclick=()=>out.textContent=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(input.value)?'Valid UUID v4':'Invalid UUID v4'});
add('hash','Hash Generator','Security','Generate SHA-1/256/384/512 locally.','hash sha crypto',field('Text','input','Text to hash')+'<select id="algo"><option>SHA-256</option><option>SHA-1</option><option>SHA-384</option><option>SHA-512</option></select>'+bar('Hash'),async()=>{try{out.textContent=hex(await crypto.subtle.digest(algo.value,new TextEncoder().encode(input.value)))}catch(e){out.textContent=e.message}});
add('password','Password Generator','Security','Generate strong passwords with browser randomness.','password random security','<label>Length<input id="length" type="number" min="8" max="128" value="20"></label><button id="generate" class="primary">Generate</button>'+input('Password','input','')+'<pre id="out" class="code"></pre>',()=>{generate.onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=',n=Math.max(8,Math.min(128,Number(length.value)||20)),a=new Uint32Array(n);crypto.getRandomValues(a);input.value=[...a].map(x=>chars[x%chars.length]).join('')}});
add('timestamp','Timestamp & DateTime','Developer Utilities','Convert Unix timestamps and ISO dates.','timestamp unix epoch iso date','<button id="now" class="primary">Current time</button>'+input('Timestamp / ISO','input','1755518400')+bar('Convert'),()=>{now.onclick=()=>input.value=Math.floor(Date.now()/1000);run.onclick=()=>{const s=input.value.trim(),n=Number(s),d=/^\d{9,13}$/.test(s)?new Date(s.length===10?n*1000:n):new Date(s);out.textContent=Number.isNaN(d.getTime())?'Invalid date':JSON.stringify({iso:d.toISOString(),local:d.toString(),unixSeconds:Math.floor(d.getTime()/1000),unixMilliseconds:d.getTime()},null,2)}});
add('regex','Regex Playground','Text & Encoding','Test matches, groups and replacements.','regex regexp replace',input('Pattern','pattern','\\b[A-Z][a-z]+\\b')+input('Flags','flags','gi')+field('Text','text','Sample text')+input('Replacement','replacement','$&')+bar('Test'),()=>{try{const re=new RegExp(pattern.value,flags.value),m=[...text.value.matchAll(new RegExp(pattern.value,flags.value.includes('g')?flags.value:flags.value+'g'))];out.textContent=JSON.stringify({matches:m.map(x=>({value:x[0],index:x.index,groups:x.groups||x.slice(1)})),replacement:text.value.replace(re,replacement.value)},null,2)}catch(e){out.textContent='Invalid regex: '+e.message}});
add('encoding','Encoding Toolkit','Text & Encoding','Base64, URL and HTML entity encoding/decoding.','base64 url html encode decode','<select id="mode"><option value="base64">Base64</option><option value="url">URL</option><option value="html">HTML entities</option></select>'+field('Input','input','Hello DevLens')+'<button id="encode" class="primary">Encode</button><button id="decode">Decode</button><pre id="out" class="code"></pre>',()=>{const htmlE=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const htmlD=s=>s.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#039;/g,"'");const run=enc=>{try{out.textContent=mode.value==='base64'?(enc?b64e(input.value):b64d(input.value)):mode.value==='url'?(enc?encodeURIComponent(input.value):decodeURIComponent(input.value)):(enc?htmlE(input.value):htmlD(input.value))}catch(e){out.textContent='Invalid input: '+e.message}};encode.onclick=()=>run(true);decode.onclick=()=>run(false)});
add('query','Query String Builder','Web & URL','Parse query parameters locally.','query params searchparams',field('Query string or URL','input','?page=2&tag=dev')+bar('Parse'),()=>{try{const raw=input.value.trim(),u=raw.includes('://')?new URL(raw):new URL('https://devlens.local/?'+raw.replace(/^\?/,'').replace(/^\?/,''));out.textContent=JSON.stringify(Object.fromEntries(u.searchParams),null,2)}catch{out.textContent='Invalid query string'}});
add('color','Color Converter & Contrast','Web & URL','Convert HEX and calculate WCAG contrast.','color hex rgb hsl contrast wcag',input('Color','input','#65e0bd')+input('Second color','second','#ffffff')+bar('Convert'),()=>{const p=h=>{let x=h.replace(/^#/,'');if(x.length===3)x=x.split('').map(c=>c+c).join('');return /^[0-9a-f]{6}$/i.test(x)?{r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4),16)}:null};const a=p(input.value),b=p(second.value);if(!a)return out.textContent='Invalid HEX color';const lum=c=>[c.r,c.g,c.b].map(x=>x/255).map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);out.textContent=JSON.stringify({rgb:'rgb('+a.r+', '+a.g+', '+a.b+')',contrast:b?Number(((Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05)).toFixed(2)):null},null,2)});
add('cidr','IP & CIDR Calculator','Developer Utilities','Calculate IPv4 network and host ranges.','ip cidr subnet ipv4',input('IPv4 / CIDR','input','192.168.1.10/24')+bar('Calculate'),()=>{const v=cidr(input.value);out.textContent=v?JSON.stringify(v,null,2):'Invalid IPv4/CIDR'});
add('case','Case Converter','Text & Encoding','Convert programming identifier casing.','camel pascal snake kebab case',field('Text','input','user profile name')+'<button data-c="camel">camelCase</button><button data-c="pascal">PascalCase</button><button data-c="snake">snake_case</button><button data-c="kebab">kebab-case</button><button data-c="constant">CONSTANT_CASE</button>',()=>document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>input.value=cases(input.value,b.dataset.c)));
add('markdown','Markdown Previewer','Text & Encoding','Preview a safe subset of Markdown locally.','markdown md preview',field('Markdown','input','# DevLens\n\n**Fast** tools.\n\n- JSON\n- API')+'<div id="preview" class="preview"></div>',()=>{const render=()=>{let x=esc(input.value);x=x.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^- (.*)$/gm,'<li>$1</li>').replace(/(?:<li>.*<\/li>\n?)+/g,m=>'<ul>'+m+'</ul>').replace(/\n/g,'<br>');preview.innerHTML='<p>'+x+'</p>'};input.oninput=render;render()});
window.DEVLENS_EXTRA_TOOLS=E;window.DEVLENS_EXTRA_UI=ui;window.DEVLENS_EXTRA_INIT=init;
})();
